-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 14, 2023 at 03:37 PM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `retrospect`
--

-- --------------------------------------------------------

--
-- Table structure for table `presidents`
--

CREATE TABLE `presidents` (
  `id` int(100) NOT NULL,
  `fullname` varchar(50) NOT NULL,
  `term` varchar(50) NOT NULL,
  `description` text NOT NULL,
  `contribution` text NOT NULL,
  `image` varchar(150) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `presidents`
--

INSERT INTO `presidents` (`id`, `fullname`, `term`, `description`, `contribution`, `image`) VALUES
(1, 'Emilio Aguinaldo ', '(January 23, 1899 – March 23, 1901)', 'Emilio Aguinaldo was the first president of the Philippines First Republic (also known as the Malolos Republic). He was inaugurated on January 23, 1899, at the Barasoain Church, Malolos, Bulacan. He led the proclamation of the Philippine Independence on June 12, 1898, in his ancestral home in Kawit, Cavite.', '•	He waved the Philippine flag in declaring the independence of the Philippines in 1898\r\n•	He was the first (and only) president of the First Republic (Malolos Republic)\r\n•	The youngest Filipino president, taking office at age 28\r\n•	The longest-lived president of the Philippines, passing away at age 94\r\n•	Featured in the front and back of the Philippine 5-peso bill (not circulated anymore)\r\n•	He led the country in the Spanish-Philippine War and the American-Philippine War\r\n•	He led the proclamation of the Philippine Independence\r\n•	Known as the President of the Revolutionary Government\r\n•	Signed the Pact of Biak-na-Bato, creating a truce between the Spanish and Philippine revolutionaries\r\n•	He was a well-known entrepreneur, soldier, and politician\r\n•	Emilio Aguinaldo had Bachelor of Arts (college preparatory) at the Colegio de San Juan de Letran in 1880\r\n\r\n', 'http://192.168.1.133/Retrospect/api/assets/emilio.jpg'),
(2, 'Manuel L. Quezon', '(1935-1944)', 'Manuel L. Quezon was the 2nd president of the Philippines and the first president of the Philippine Commonwealth established under the USA. He was inaugurated on December 30, 1941, in Corregidor Island. He’s known as the “Father of National Language” (Ama ng Wikang Pambansa). He died of tuberculosis in Saranac Lake, New York.', '•	First President elected through a national election\r\n•	First Senate President elected as President of the Philippines\r\n•	The first president of the Philippines under the Commonwealth\r\n•	Initiated women’s suffrage in the Philippines during the Commonwealth\r\n•	Manuel L. Quezon created the National Council of Education\r\n•	He approved Filipino as the national language of the Philippines\r\n•	Studied Bachelor of Arts at Colegio de San Juan de Letran\r\n•	Studied Bachelor of Law at the University of Sto. Tomas\r\n•	Ranked 4th in the Philippine Bar Exam (1903)\r\n•	A province, a city, a bridge, and a university in Manila are named after him\r\n•	He fought for the passage of the Tydings-McDuffie Act (1934)\r\n•	His body rests peacefully inside the special monument on Quezon Memorial Circle\r\n•	Featured in the 20-peso bill, for the Declaration of Filipino as the national language\r\n•	First Filipino featured on the cover of TIME Magazine\r\n', 'http://192.168.1.133/Retrospect/api/assets/manuel1.jpg'),
(3, 'Jose P. Laurel ', 'Laurel (October 14, 1943 – August 17, 1945)', 'Jose P. Laurel was the 3rd president of the Philippines and the president of the Second Philippine Republic. His inauguration was on October 14, 1943, in the Legislative Building, now National Museum. He served president of the Philippines during the Japanese occupation during World War II.', '•	Jose P. Laurel is the only Philippine president who served the three branches of government – he became a senator-congressman, associate justice, and president\r\n•	Since the early 1960s, Laurel was recognized as a legitimate president of the Philippines\r\n•	Organized KALIBAPI (Kapisanan sa Paglilingkod sa Bagong Pilipinas, or Association for Service to the New Philippines), a provisional government during the Japanese occupation\r\n•	Laurel declared Martial Law and war between the Philippines and the US/United Kingdom in 1944\r\n•	He’s the Founder of the Lyceum of the Philippines\r\n•	He’s a Law genius, ranked 2nd in the Philippine Bar Exam in 1915\r\n•	Earned a Doctorate in Civil Law from Yale University in 1920\r\n•	Received Honoris Causa from Tokyo Imperial University in 1938\r\n•	He was assassinated twice, but he survived and recovered\r\n', 'http://192.168.1.133/Retrospect/api/assets/Jose.webp'),
(4, 'Sergio Osmeña Sr.', '(August 1, 1944 – May 28, 1946)', 'Sergio Osmeña Sr. was the 4th president of the Philippines and the 2nd president of the Commonwealth. He was inaugurated on August 1, 1944, in Washington DC. He succeeded the presidency after the death of then president Manuel L. Quezon. During his administration, the Philippines joined the International Monetary Fund.', '•	Sergio Osmeña was the first Visayan to become president, born in Cebu City\r\n•	He joined with U.S. Gen. Douglas McArthur in Leyte on October 20, 1944, to begin restoration of Philippine freedom after Japanese occupation\r\n•	Founder of the Nacionalista Party\r\n•	Philippine National Bank was rehabilitated, and the country joined the International Monetary Fund during his presidency\r\n•	The U.S. Congress approved the Bell Trade Act during his presidency\r\n•	He was 2nd placer in the 1903 Philippine Bar Exam\r\n•	Founder and Editor of a Spanish newspaper, El Nuevo Dia, in Cebu City\r\n•	Had Bachelor of Arts from Colegio de San Juan de Letran (1894)\r\n•	Had Bachelor of Law from the University of Santo Tomas (1903)\r\n•	Featured in the 50-peso bill, First Philippine Assembly, Leyte Landing\r\n', 'http://192.168.1.133/Retrospect/api/assets/Sergio.webp'),
(5, 'Manuel A. Roxas ', '(May 28, 1946 – April 15, 1948)', 'Manuel Roxas was the 5th president of the Philippines, the 3rd (and last) president under the Commonwealth, and the first president of the Third Republic of the Philippines. He was inaugurated on May 28, 1946, at the National Museum building. He held office for only one year, 10 months, and 18 days.', '•	Manuel Roxas was inaugurated as the first president of the New Republic after World War II\r\n•	Reconstruction from war damage and life without foreign rule began during his presidency\r\n•	Congress accepted the Philippine Rehabilitation Act and Philippine Trade Act laws under his term\r\n•	Ranked 1st Place in the Philippine Bar Exam (1913)\r\n•	Featured in the 100-peso bill, Old Bangko Sentral ng Pilipinas building in Intramuros, Manila, Inauguration of the Third Philippine Republic\r\n\r\n', 'http://192.168.1.133/Retrospect/api/assets/Manuel.webp'),
(6, 'Elpidio R. Quirino ', '(April 17, 1948 – December 30, 1953)', 'Elpidio Quirino was the 6th president of the Philippines and the 2nd president of the Third Republic. He succeeded presidency after incumbent president Manuel Roxas died in 1948. Quirino was 57 years old when he was inaugurated as president on April 17, 1948, at the Malacañang Palace.', '•	Hukbalahap Guerrilla movement was active during his presidency\r\n•	He created the Social Security Commission\r\n•	He created the Integrity Board to monitor graft and corruption\r\n•	During his term, Quezon City became capital of the Philippines in 1948\r\n•	Completed Bachelor of Law at the University of the Philippines in 1915\r\n•	Dean of the College of Law at the Adamson University (1941-1946)\r\n•	Ranked 2nd placer in the Philippine Bar Exam in 1915\r\n\r\n', 'http://192.168.1.133/Retrospect/api/assets/Elpidio.webp'),
(7, 'Ramon Magsaysay Sr. ', '(December 30, 1953 – March 17, 1957)', 'Ramon Magsaysay was the 7th president of the Philippines and the 3rd president of the Third Republic. He was the first president who sworn into the office wearing Barong Tagalog during the inauguration. He died in an aircraft disaster while boarding the presidential plane.', '•	He led to defeat the Hukbalahap movement\r\n•	Chairman of the Committee on Guerrilla Affairs\r\n•	His presidency was referred to as the Philippines’ “Golden Years” for its lack of corruption\r\n•	The Philippines was ranked second in Asia’s clean and well-governed countries during his presidency\r\n•	He established the National Resettlement and Rehabilitation Administration (NARRA) among other agrarian reforms\r\n•	He made the Philippine a member of the Southeast Asia Treaty Organization\r\n', 'http://192.168.1.133/Retrospect/api/assets/Ramon_Magsaysay.webp'),
(8, 'Carlos P. Garcia', '(March 18, 1957 – December 30, 1961)', 'Carlos P. Garcia is the 8th president of the Philippines and fourth president of the Third Republic. This Bohol native was a lawyer, poet, and professor and served as a guerrilla leader during the Pacific War. Garcia served as vice president under Ramon Magsaysay and as secretary of Foreign Affairs for four years. He became president when Magsaysay died in a plane crash in 1957.', '•	Carlos P. Garcia was known for promoting “Filipino First Policy,” which favored Filipino businesses over foreign investors\r\n•	He established the Austerity Program focusing on Filipino trade and commerce\r\n•	He became a famous poet and known as the “Prince of Visayan Poets” and the “Bard from Bohol.”\r\n•	Cultural arts was revived during his term\r\n•	He was the first president to have his remains buried at the Libingan ng mga Bayani\r\n•	He achieved 7th placer in the Philippine Bar Exam in 1923\r\n\r\n', 'http://192.168.1.133/Retrospect/api/assets/Carlos_Garcia.webp'),
(9, 'Diosdado P. Macapagal ', '(December 30, 1961 – December 30, 1965)', 'Diosdado P. Macapagal was the 9th president of the Philippines. He was a lawyer and economist, born in Lubao, Pampanga. He was inaugurated on December 30, 1961, at the Quirino Grandstand. His daughter, Gloria Macapagal Arroyo, followed his path and became president, too.\r\n\r\n', '•	Topped the Bar Exam, 1st place in 1936\r\n•	Took a Master of Law in 1941 and Doctor of Civil Law in 1947, and a Ph.D. in Economics in 1957\r\n•	Diosdado Macapagal was a great economist, he established the first Land Reform Law, allowing for the purchase of private farmland to be distributed in inexpensive, small lots to the landless\r\n•	He placed the Philippine peso on the free currency exchange market and encouraged exports\r\n•	The Philippine representative to the United Nations General Assembly three times\r\n•	He signed the Minimum Wage Law\r\n•	Diosdado Macapagal signed the law to create the Philippine Veteran’s Bank\r\n•	Featured in the 200-peso bill\r\n\r\n', 'http://192.168.1.133/Retrospect/api/assets/Diosdado_macapagal.webp'),
(10, 'Ferdinand E. Marcos ', '(December 30, 1965 – February 25, 1986)', 'Ferdinand Marcos was the tenth president of the Philippines and the last president of the Third Republic. He was one of the most controversial leaders of the 20th century. He ruled the Philippines for 21 years and was removed from office after the People Power Revolution.\r\n\r\n', '•	The first president to win a second term\r\n•	The longest-ruling president of the Philippines, he ruled for 21 years\r\n•	He declared Martial Law on Sept. 22, 1972\r\n•	He increased the size of Philippine military and armed forces\r\n•	By 1980, the Philippine GNP was four times greater than 1972\r\n•	Marcos built more schools, roads, bridges, hospitals, and other infrastructure than all former presidents combined\r\n•	He topped 1st place in the Bar Exam in 1939\r\n•	The only president whose remains were interred inside a refrigerated crypt\r\n•	Many of Marcos Sr.’s infrastructure projects include the North Luzon Expressway, South Luzon Expressway, Maharlika Highway, Circumferential Roads 1-10, San Juanico Bridge, and Mactan-Mandaue Bridge\r\n•	Ferdinand Marcos Sr.’s government also completed 20 power plants so that the Philippines would be independent of the surging prices of oil and electricity\r\n•	Notable medical institutions were also built during Marcos’s regime, such as the Philippine Heart Center, Lung Center of the Philippines, and National Kidney and Transplant Institute\r\n•	The Cultural Center of the Philippines (CCP), Folks Arts Theater, Philippine International Convention Center (PICC), National Arts Center, Nayong Pilipino, and the People’s Park in the Sky were constructed during Marcos Sr.’s regime to promote Filipino heritage and culture\r\n•	Marcos Sr. signed the Emancipation of Tenants from the Bondage of the Soil (Presidential Decree No.27) in 1972\r\n', 'http://192.168.1.133/Retrospect/api/assets/Ferdinand_Marcos.webp'),
(11, 'Corazon C. Aquino ', '(February 25, 1986 – June 30, 1992)', 'Corazon Aquino was the first woman president of the Philippines and the first woman to become president of an Asian country. She was the 11th president and a democracy icon, one of the 100 Women Who Shaped World History and 20 Most Influential Asians of the 20th Century.\r\n\r\n', '•	The first woman to be president of the Philippines or any Asian country\r\n•	She signed the Family Code of 1987, a major civil law reform, and 1191 Local Government Code, which reorganized the structure of the executive branch of government\r\n•	She initiated charitable and social activities helping the poor and the needy\r\n•	Was named “Woman of the Year” in 1986 by TIME magazine\r\n•	She was featured on the new 500-peso bill together with her husband, Benigno Aquino Jr.\r\n•	Among the 100 Women Who Shaped World History\r\n•	One of the 20 Most Influential Asians of the 20th Century\r\n•	One of TIME Magazine’s 65 Asian Heroes\r\n•	Received Honorary Doctorates from international universities including Boston University, Eastern University in Pennsylvania, Fordham University in New York, Waseda University in Tokyo\r\n', 'http://192.168.1.133/Retrospect/api/assets/Corazon_Aquino.webp'),
(12, 'Fidel V. Ramos ', '(June 30, 1992 – June 30, 1998)', 'Fidel Ramos was the 12th president of the Philippines. Ramos also lived longer than the other presidents. Like Aguinaldo, FVR was 94 years old when he died. He’s one of the most admired presidents because, during his presidency, he restored economic growth and stability in the country.', '•	FVR was widely credited as the most effective president because he led the Philippines to economic growth\r\n•	He promoted family-planning practices to help to solve the country’s growing population\r\n•	Hosted the 4th Asia Pacific Economic Cooperation Leader’s Summit in the Philippines in 1996\r\n•	He presided over celebrations of Philippine Independence Centennial in 1998\r\n•	Ramos reached out peace talks with the rebels such as the Moro National Liberation Front and New People’s Army\r\n•	FVR received British Knighthood from Her Majesty Queen Elizabeth II (Knight Grand Cross of the Order of St. Michael and St. George)\r\n•	The Philippine Stock Exchange became an international favorite during his presidency\r\n•	Ranked 8th Place in the Philippine Civil Engineering Licensure Exam (1953)\r\n•	The death penalty was reinstated while he was in office\r\n•	FVR was the only military officer who reached the rank of five-star general/admiral de jure who rose from second lieutenant up to commander-in-chief of the armed forces\r\n•	Had 29 Honorary Doctorate Degrees\r\n\r\n', 'http://192.168.1.133/Retrospect/api/assets/Fidel_Ramos.webp'),
(13, 'Joseph E. Estrada ', '(June 30, 1998 – January 20, 2001)', 'Joseph Estrada is the 13th president of the Philippines and the first film actor to become a president in the country. During his years in office, economic growth was slow, and he faced impeachment proceedings. He became the first president in Asia to be impeached from an executive role. He was ousted from the presidency in 2001.', '•	He starred in over 100 films in the Philippines and received numerous Best Actor awards\r\n•	Moro Islamic Liberation Front headquarters and camps were captured during his presidency\r\n•	Cited as one of the Three Outstanding Senators in 1989\r\n•	He became a Mayor of the City of Manila, the county’s capital\r\n•	He won every mayor election in San Juan from 1969 to 1984\r\n•	Erap was among the “Magnificent 12” who voted to terminate the agreement that allows for U.S. control of Clark Airbase and Subic Naval Base\r\n•	He was credited with the passage of, among other pieces of legislation, the bills on irrigation project and the protection of carabaos\r\n', 'http://192.168.1.133/Retrospect/api/assets/Joseph_Estrada.webp'),
(14, '. Gloria Macapagal Arroyo ', '(January 20, 2001 – June 30, 2010)', 'Gloria Macapagal Arroyo is the 14th president of the Philippines, the 2nd female president, and the first Filipino president whose parent was a former president. She’s also an economist like her father, ex-president Diosdado Macapagal. Having a master’s degree and doctorate in economics, Gloria put the Philippine economy back in shape.\r\n\r\nAnnual economic growth in the Philippines averaged 4.5% during her administration, expanding every quarter of her presidency. That is higher than in the administrations of her three immediate predecessors. The peso strengthened by nearly 20% in making it the best-performing currency of the year in 2007.\r\n', '•	Second female president of the country\r\n•	First president to take oath outside Luzon\r\n•	Gloria Arroyo oversaw higher economic growth than the past three presidents before her\r\n•	Philippine Peso became the best-performing currency of the year in Asia in 2007 during her term\r\n•	eVAT Law was implemented under her term\r\n•	She supported to bring back Spanish language in the Philippines during her 9-year presidency\r\n•	She took up International Trade at Georgetown University in Washington D.C. with Bill Clinton\r\n•	Graduated Magna Cum Laude from Assumption College in 1968\r\n•	Arroyo earned a Master’s Degree in Economics from Ateneo de Manila University in 1978\r\n•	Obtained Doctorate in Economics from the University of the Philippines in 1986\r\n•	Numerous Honorary Degrees granted by prominent international universities\r\n•	TIME Magazine’s People Who Mattered list for 2005\r\n•	Forbes 100 Most Powerful Women in the World (2004 – 2009)\r\n•	Currently featured on the 200-peso bill\r\n', 'http://192.168.1.133/Retrospect/api/assets/Gloria_Macapagal-Arroyo.webp'),
(15, 'Benigno Aquino III ', '(June 30, 2010 – June 30, 2016)', 'Benigno Aquino III was the 15th president of the Philippines. He was the first bachelor president. A son of ex-president Corazon Aquino, he was also called as Noynoy or PNoy. Noynoy finished his Economics degree from Ateneo de Manila University. He was one of the students of a former economics professor, Gloria Macapagal Arroyo, the president before him.', '•	He created the no “wang-wang” (street siren) policy\r\n•	Noynoy initiated shifting to K-12 education in the Philippines\r\n•	Peace agreement with the Moro Islamic Liberation Front in October 2012\r\n•	Oversaw 7.1% growth of the Philippine economy in 2012\r\n•	TIME named him one of the 100 Most Influential People in the World in 2013\r\n\r\n', 'http://192.168.1.133/Retrospect/api/assets/Benigno_Aquino_III.webp'),
(16, 'Rodrigo Roa Duterte ', '(June 30, 2016 – June 30, 2022)', 'Rodrigo Roa Duterte is the 16th president of the Philippines. He’s one of the most loved presidents. He’s earned a massive fanbase after transforming one of the most dangerous cities (Davao) into one of the world’s safest when he was a mayor. At age 71, he became the oldest Filipino ever elected to the presidency.', '•	He earned Political Science Degree from Lyceum of the Philippines in 1968\r\n•	Obtained Law Degree from San Beda College in 1972\r\n•	He initiated decongesting the Ninoy Aquino International Airport in Manila, the country’s main gateway\r\n•	Signed the Freedom of Information Order\r\n•	Duterte launched a 24-hour complaint hotline, 8888\r\n•	He signed an order for Smoking Ban in public places\r\n•	Boracay Island was rehabilitated during his term\r\n•	Launched the Build! Build! Build! Infrastructure Program\r\n•	Duterte signed the TRAIN Law and Comprehensive Tax Reform Program\r\n•	One of Forbes list of World’s Most Powerful People in 2016\r\n•	Duterte has been featured on the cover of TIME Magazine\r\n', 'http://192.168.1.133/Retrospect/api/assets/Rodrigo_Duterte.webp'),
(17, 'Ferdinand R. Marcos Jr.', '(June 30, 2022 – present)', 'Ferdinand R. Marcos Jr. is the 17th president of the Philippines. He is the second child of former president Ferdinand Edralin Marcos and the “iron butterfly” Imelda Romualdez Marcos. His campaign is focused on unity. BBM won the presidential election by a landslide garnering over 31 million votes.', '•	BBM has been a public servant since 1980\r\n•	He served as a senator, congressman, governor, and vice-governor\r\n•	Marcos Jr. authored landmark laws such as the Philippine Archipelagic Baselines Law (R.A. 9522)\r\n•	He authored, co-authored, sponsored, and co-sponsored 54 bills passed into law\r\n•	BBM led the modernization of agricultural and tourism landscape of Ilocos Norte when he was a governor\r\n•	BBM is an advocate of renewable energy and sustainable development, the Bangui Windmill Farm was one of his astonishing energy development projects\r\n', 'http://192.168.1.133/Retrospect/api/assets/PBBM.webp');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `presidents`
--
ALTER TABLE `presidents`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `presidents`
--
ALTER TABLE `presidents`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
